# Generated by Django 3.1.2 on 2020-10-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201022_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteBanners',
            new_name='SiteBanner',
        ),
    ]
